name: RobotCore
version: '${project.version}'
main: fr.robotv2.robotcore.core.RobotCore
api-version: 1.18
depend:
  - Vault
commands:
  jobs:
    usage: /<command>
    description: The main command for the job module.
    aliases:
      - job